import {
  AddressBookTabsIcon,
  AirplaneIcon,
  AlarmIcon,
  AvocadoIcon,
  BarcodeIcon,
  BellIcon,
  BicycleIcon,
  BluetoothIcon,
  BoneIcon,
  BowlSteamIcon,
  BrainIcon,
  BroomIcon,
  BrowsersIcon,
  CameraIcon,
  CarrotIcon,
  ChartBarIcon,
  ChefHatIcon,
  CpuIcon,
  DropIcon,
  FeatherIcon,
  FloppyDiskIcon,
  GameControllerIcon,
  HamburgerIcon,
  HandPeaceIcon,
  IceCreamIcon,
  LegoIcon,
  LightningIcon,
  MapPinIcon,
  MeteorIcon,
  MountainIcon,
  MouseMiddleClickIcon,
  OnigiriIcon,
  PenNibIcon,
  RadioactiveIcon,
  ThumbsUpIcon,
  TruckTrailerIcon,
  VideoConferenceIcon,
  WavesIcon,
  WindmillIcon,
  YarnIcon,
} from '@/components/Icons';
import { IconName } from '@/lib/models/icons';

const iconList = [
  { name: 'AddressBookTabsIcon', component: AddressBookTabsIcon },
  { name: 'AirplaneIcon', component: AirplaneIcon },
  { name: 'AlarmIcon', component: AlarmIcon },
  { name: 'AvocadoIcon', component: AvocadoIcon },
  { name: 'BarcodeIcon', component: BarcodeIcon },
  { name: 'BellIcon', component: BellIcon },
  { name: 'BicycleIcon', component: BicycleIcon },
  { name: 'BluetoothIcon', component: BluetoothIcon },
  { name: 'BoneIcon', component: BoneIcon },
  { name: 'BowlSteamIcon', component: BowlSteamIcon },
  { name: 'BrainIcon', component: BrainIcon },
  { name: 'BroomIcon', component: BroomIcon },
  { name: 'BrowsersIcon', component: BrowsersIcon },
  { name: 'CameraIcon', component: CameraIcon },
  { name: 'CarrotIcon', component: CarrotIcon },
  { name: 'ChartBarIcon', component: ChartBarIcon },
  { name: 'ChefHatIcon', component: ChefHatIcon },
  { name: 'CpuIcon', component: CpuIcon },
  { name: 'DropIcon', component: DropIcon },
  { name: 'FeatherIcon', component: FeatherIcon },
  { name: 'FloppyDiskIcon', component: FloppyDiskIcon },
  { name: 'GameControllerIcon', component: GameControllerIcon },
  { name: 'HamburgerIcon', component: HamburgerIcon },
  { name: 'HandPeaceIcon', component: HandPeaceIcon },
  { name: 'IceCreamIcon', component: IceCreamIcon },
  { name: 'LegoIcon', component: LegoIcon },
  { name: 'LightningIcon', component: LightningIcon },
  { name: 'MapPinIcon', component: MapPinIcon },
  { name: 'MeteorIcon', component: MeteorIcon },
  { name: 'MountainIcon', component: MountainIcon },
  { name: 'MouseMiddleClickIcon', component: MouseMiddleClickIcon },
  { name: 'OnigiriIcon', component: OnigiriIcon },
  { name: 'PenNibIcon', component: PenNibIcon },
  { name: 'RadioactiveIcon', component: RadioactiveIcon },
  { name: 'ThumbsUpIcon', component: ThumbsUpIcon },
  { name: 'TruckTrailerIcon', component: TruckTrailerIcon },
  { name: 'VideoConferenceIcon', component: VideoConferenceIcon },
  { name: 'WavesIcon', component: WavesIcon },
  { name: 'WindmillIcon', component: WindmillIcon },
  { name: 'YarnIcon', component: YarnIcon },
] as const;

export const RandomIconComponents = Object.fromEntries(
  iconList.map(({ name, component }) => [name, component]),
);

export function generateRandomIcons(count: number): IconName[] {
  return Array.from(
    { length: count },
    () => iconList[Math.floor(Math.random() * iconList.length)].name,
  );
}
